# https://pre-commit.com/hooks.html

ci:
  skip:
    - copyright
    - poetry-lock
    - poetry-check
    - ripsecrets
    - jsonschema-validator
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: name-tests-test
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-json
  - repo: https://github.com/sbrunner/hooks
    rev: 0.5.0
    hooks:
      - id: copyright
      - id: workflows-require-timeout
      - id: poetry-check
        additional_dependencies:
          - poetry==1.3.2 # pypi
      - id: poetry-lock
        additional_dependencies:
          - poetry==1.3.2 # pypi
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --pre-summary-newline
    # - repo: https://github.com/PyCQA/prospector
    #   rev: v1.8.4
    #   hooks:
    #     - id: prospector
    #       args: [--tool=pydocstyle, --die-on-tool-error]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --ignore-words=.github/spell-ignore-words.txt
        exclude: ^poetry.lock$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.0 # npm
          - prettier-plugin-sh@0.13.1 # npm
          - prettier-plugin-toml@0.3.1 # npm
        exclude: |-
          (?x)^(
              \.gitattributes
              |\.gitignore
          )$
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-github-workflows
      - id: check-renovate
        additional_dependencies: [pyjson5]
      - id: check-github-actions
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets.git
    rev: v0.1.5
    hooks:
      - id: ripsecrets
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.5
    hooks:
      - id: ripsecrets
  - repo: https://github.com/PyCQA/prospector
    rev: 1.10.2
    hooks:
      - id: prospector
        args:
          - --tool=pydocstyle
          - --die-on-tool-error
          - --output-format=pylint
        additional_dependencies:
          - prospector-profile-duplicated==0.1.0 # pypi
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.1.0
    hooks:
      - id: jsonschema-validator
        files: |-
          (?x)^(
              ci/config\.yaml
          )$
