inherits:
  - utils:base
  - utils:no-design-checks
  - duplicated

doc-warnings: true

pydocstyle:
  disable:
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__

bandit:
  options:
    config: .bandit.yaml
